PdxLocalBusinessesClient/Controllers/BusinessesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System;
using PdxLocalBusinessesClient.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PdxLocalBusinessesClient.Controllers
{
	public class BusinessesController : Controller
	{

		public IActionResult Index()
		{
			var allBusinesses = Business.GetBusinesses();
			return View(allBusinesses);
		}

		// public ActionResult Details(int id)
		// {
		// 	var thisBusiness = Business.GetMsgDetails(id);
		// 	return View(thisBusiness);
		// }

		// public ActionResult Create()
		// {
    //   var neighborhoods = Neighborhood.GetNeighborhoods();
		// 	ViewBag.NeighborhoodId = new SelectList(neighborhoods, "NeighborhoodId", "Name");
		// 	return View();
		// }

		// [HttpPost]
		// public ActionResult Create(Business business, int NeighborhoodId)
		// {
		// 	if (NeighborhoodId != 0)
		// 	{
		// 		business.NeighborhoodId = NeighborhoodId;
		// 	}
		// 	Business.PostMsg(business);
    //   return RedirectToAction("Details", new {id = business.BusinessId});
		// }

		// public ActionResult Edit(int id)
		// {
		// 	var thisBusiness = Business.GetMsgDetails(id);
		// 	var neighborhoods = Neighborhood.GetNeighborhoods();
		// 	ViewBag.NeighborhoodId = new SelectList(neighborhoods, "NeighborhoodId", "Name");
		// 	return View(thisBusiness);
		// }

		// [HttpPost]
    // public ActionResult Edit(Business business)
    // {
    //   Business.PutMsg(business);
    //   return RedirectToAction("Details", new { id = business.BusinessId });
    // }

    // [HttpPost]
    // public ActionResult Delete(int id)
    // {
    //   Business.DeleteMsg(id);
    //   return RedirectToAction("Index");
    // }
	}
}

PdxLocalBusinessesClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Portland Local Businesses</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portland Local Businesses</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Businesses" asp-action="Index">Businesses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PdxLocalBusinessesClient<a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>